version: 2
jobs:
  build:
    docker:

      - image: circleci/node:6

    working_directory: ~/flights_cache_admin

    steps:

      - checkout

      - setup_remote_docker

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Running Unit Tests
          command: yarn test

      - run:
          name: Creating a Build
          command: yarn run build

      - run:
          name: Building Docker Image
          command: docker build --tag flights-cache-admin:1 .

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
